'use strict';
const core = window.ColdCoffeeCore;
const $ = (id) => document.getElementById(id);
const state = {seat:'codex',profile:'max',history:[],counter:0,result:null,busy:false};
let toastTimer;
function toast(message) { $('toast').textContent=message; $('toast').classList.add('visible'); clearTimeout(toastTimer); toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3500); }
function button(text,click,cls='') { const b=document.createElement('button'); b.type='button'; b.textContent=text; b.className=cls; b.addEventListener('click',click); return b; }
function page(name) { document.querySelectorAll('.page').forEach(el=>el.classList.toggle('active',el.id===`page-${name}`)); document.querySelectorAll('.nav').forEach(el=>{const yes=el.dataset.page===name;el.classList.toggle('active',yes);el.setAttribute('aria-current',yes?'page':'false');}); }
function renderSeats() { $('seats').replaceChildren(...core.SEATS.map(s=>{const b=button('',()=>{state.seat=s.id;renderSeats();window.dispatchEvent(new CustomEvent("coldcoffee:seat",{detail:s.id}));toast(`当前席位：${s.tag}（配置席位已切换）`);},`seat${state.seat===s.id?' selected':''}`);b.setAttribute('aria-pressed',String(state.seat===s.id)); const mark=document.createElement('span');mark.className='mark';mark.textContent=s.mark;b.append(mark,document.createTextNode(s.tag));return b;})); const seat=core.SEATS.find(s=>s.id===state.seat); $('seat-title').textContent=seat.tag;$('seat-hint').textContent=seat.hint; }
function renderProfiles() { $('profiles').replaceChildren(...core.PROFILES.map(p=>{const b=button(p.label,()=>{state.profile=p.id;renderProfiles();},state.profile===p.id?'active':'');b.title=p.brief;b.setAttribute('aria-pressed',String(state.profile===p.id));return b;})); }
function revisions() { for(const id of ['before','after']) {$(id).replaceChildren(...state.history.map(h=>{const opt=document.createElement('option');opt.value=String(h.id);opt.textContent=`版本 ${h.id} · ${h.seat} · ${h.time}`;return opt;}));} $('before').value=String(state.history[Math.max(0,state.history.length-2)].id);$('after').value=String(state.history.at(-1).id); compare(); }
function compare() { const a=state.history.find(h=>String(h.id)===$('before').value),b=state.history.find(h=>String(h.id)===$('after').value); if(!a||!b)return;const diff=core.diff(a.text,b.text);$('removed').textContent=diff.removed.join('\n')||'无删除内容';$('added').textContent=diff.added.join('\n')||'无新增内容';$('diff-note').textContent=diff.same?'两个版本文本一致。':`前 ${diff.prefix} 行一致；显示中间变更区段（整体替换视图，不是逐行最小差异）。`; }
async function compose(event) {event?.preventDefault();if(state.busy)return;state.busy=true;const submit=$('compose-form').querySelector('[type=submit]');submit.disabled=true;try{const input={goal:$('goal').value,context:$('context').value,constraints:$('constraints').value,format:$('format').value,seat:state.seat,profile:state.profile};const result=window.coldbrew?.compose?await window.coldbrew.compose(input):core.compose(input);state.result=result;state.history.push({id:++state.counter,text:result.text,seat:core.SEATS.find(s=>s.id===state.seat).tag,time:new Date().toLocaleTimeString('zh-CN',{hour12:false})});if(state.history.length>20)state.history.shift();$('empty-output').hidden=true;$('output').hidden=false;$('output').textContent=result.text;$('output-stat').textContent=`${result.sections} 个区段 · ${result.characters} 字符`;$('revision').textContent=`版本 ${state.counter} · 当前会话`;$('checks').replaceChildren(...result.checks.map(c=>{const el=document.createElement('span');el.textContent=`${c.ok?'✓':'○'} ${c.name}`;return el;}));$('checks').classList.add('done');$('copy').disabled=false;$('export').disabled=false;revisions();toast('任务契约已构建；尚未向模型发送。');}catch(e){toast(e.message);}finally{state.busy=false;submit.disabled=false;}}
async function copy(text) {try{await navigator.clipboard.writeText(text);toast('已复制');}catch{toast('剪贴板暂不可用，请选中文本手动复制。');}}
function download() {if(!state.result)return;const blob=new Blob([state.result.text],{type:'text/markdown;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`冷咖啡-${state.result.task.seat}-v${state.counter}.md`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已导出当前版本');}
function renderCommunity() {$('community').replaceChildren(...core.COMMUNITY.map((group,index)=>{const card=document.createElement('article');card.className='community-card';const label=document.createElement('div');label.className='eyebrow';label.textContent=`冷咖啡 / 0${index+1}`;const title=document.createElement('h2');title.textContent=group.name;const qr=button('',()=>{$('qr-large').src=img.src;$('qr-caption').textContent=`${group.name} · ${group.value}`;$('qr-dialog').showModal();},'qr-button');qr.setAttribute('aria-label',`放大${group.name}二维码`);const img=document.createElement('img');img.src=`../../assets/community/${group.image}`;img.alt=`${group.name}二维码，群号 ${group.value}`;qr.append(img);const row=document.createElement('div');row.className='group-number';const value=document.createElement('code');value.textContent=group.value;row.append(value,button('复制群号',()=>copy(group.value)));card.append(label,title,qr,row);return card;}));}
document.querySelectorAll('.nav').forEach(b=>b.addEventListener('click',()=>page(b.dataset.page)));
$('presets').replaceChildren(...core.PRESETS.map(p=>button(p.label,()=>{$('goal').value=p.goal;$('context').value=p.context;$('constraints').value=p.constraints;$('format').value=p.format;state.profile=p.profile;renderProfiles();toast('已填入示例，编辑后点击冷咖啡启动');})));
$('compose-form').addEventListener('submit',compose);$('copy').addEventListener('click',()=>copy(state.result.text));$('export').addEventListener('click',download);$('before').addEventListener('change',compare);$('after').addEventListener('change',compare);
$('eval-form').addEventListener('submit',async event=>{event.preventDefault();try{const answer=$('answer').value,options={format:$('eval-format').value,minLength:Number($('min-length').value),keywords:$('keywords').value};const r=window.coldbrew?.evaluate?await window.coldbrew.evaluate(answer,options):core.evaluate(answer,options);$('eval-score').textContent=`${r.passed} / ${r.total} 项通过`;$('eval-result').replaceChildren(...r.checks.map(c=>{const line=document.createElement('div');line.className=c.ok?'pass':'fail';line.textContent=`${c.ok?'✓':'×'} ${c.name}`;return line;}));}catch(e){toast(e.message);}});
$('qr-close').addEventListener('click',()=>$('qr-dialog').close());$('qr-dialog').addEventListener('click',e=>{if(e.target===$('qr-dialog'))$('qr-dialog').close();});
$('repo').addEventListener('click',()=>{const url='https://github.com/3641397194-wq/gpt6-Astra';if(window.coldbrew)window.coldbrew.openExternal(url).catch(e=>toast(e.message));else window.open(url,'_blank','noopener,noreferrer');});
if(window.coldbrew){document.body.classList.add('desktop');$('environment').textContent='桌面端 · 本地构建';for(const name of ['minimize','maximize','close'])$(name).addEventListener('click',()=>window.coldbrew[name]());}
document.addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key==='Enter'&&$('page-work').classList.contains('active')){event.preventDefault();$('compose-form').requestSubmit();}});
renderSeats();renderProfiles();renderCommunity();
