'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {SeatTransactions}=require('../src/lib/seat-transactions');
const fixtures=path.resolve(__dirname,'../../.coldbrew/transaction-tests');fs.mkdirSync(fixtures,{recursive:true});
function fixture(fn){const home=fs.mkdtempSync(path.join(fixtures,'case-'));try{return fn(home);}finally{const resolved=path.resolve(home);assert.ok(resolved.startsWith(fixtures+path.sep));fs.rmSync(resolved,{recursive:true,force:true});}}
test('no global target fallback',()=>{const tx=new SeatTransactions();assert.throws(()=>tx.preview('codex'),/选择/);assert.throws(()=>tx.select(path.parse(fixtures).root));});
for(const seat of ['codex','claude','grok','deepseek','glm53','gemini'])test(`${seat}: real preview/write/hash-verify/restore`,()=>fixture(home=>{
 const tx=new SeatTransactions();tx.select(home);const p=tx.preview(seat);assert.ok(p.files.length>6);assert.ok(p.packHash.length===64);assert.equal(tx.history().length,0);assert.equal(fs.readdirSync(home).length,0);
 const first=tx.file(p.id,0);assert.ok(first.after.length>0);const applied=tx.deploy(p.id);assert.equal(applied.changed,p.files.length);assert.ok(fs.existsSync(applied.backup));assert.equal(tx.verify(seat).ok,true);
 const again=tx.preview(seat);assert.equal(again.changes,0);assert.equal(tx.deploy(again.id).changed,0);const restored=tx.restore(applied.id);assert.equal(restored.restored,p.files.length);for(const f of p.files)assert.equal(fs.existsSync(path.join(home,f.path)),false);assert.equal(tx.history()[0].status,'restored');
}));
test('existing bytes restored exactly; TOML root insertion stays before sections',()=>fixture(home=>{
 const original=Buffer.from('\uFEFF# original\r\n[other]\r\nenabled = true\r\n');fs.writeFileSync(path.join(home,'config.toml'),original);const agent=Buffer.from('keep these notes\r\n');fs.writeFileSync(path.join(home,'AGENTS.md'),agent);const tx=new SeatTransactions();tx.select(home);const p=tx.preview('codex');const f=tx.file(p.id,p.files.findIndex(f=>f.path==='config.toml'));assert.ok(f.after.indexOf('model_instructions_file')<f.after.indexOf('[other]'));const a=tx.deploy(p.id);tx.restore(a.id);assert.deepEqual(fs.readFileSync(path.join(home,'config.toml')),original);assert.deepEqual(fs.readFileSync(path.join(home,'AGENTS.md')),agent);
}));
test('reject invalid JSON without touching it',()=>fixture(home=>{const file=path.join(home,'settings.json');fs.writeFileSync(file,'{broken');const tx=new SeatTransactions();tx.select(home);assert.throws(()=>tx.preview('gemini'));assert.equal(fs.readFileSync(file,'utf8'),'{broken');}));
test('concurrent file changes block deployment and restore',()=>fixture(home=>{const tx=new SeatTransactions();tx.select(home);const p=tx.preview('claude');fs.writeFileSync(path.join(home,'CLAUDE.md'),'external');assert.throws(()=>tx.deploy(p.id),/其他操作/);const q=tx.preview('claude'),a=tx.deploy(q.id);fs.appendFileSync(path.join(home,'CLAUDE.md'),'\nuser edit');assert.throws(()=>tx.restore(a.id),/其他操作/);assert.match(fs.readFileSync(path.join(home,'CLAUDE.md'),'utf8'),/user edit$/);}));
test('junction escape rejected',()=>fixture(home=>{const target=path.join(home,'outside');fs.mkdirSync(target);const selected=path.join(home,'selected');fs.mkdirSync(selected);fs.symlinkSync(target,path.join(selected,'skills'),'junction');const tx=new SeatTransactions();tx.select(selected);assert.throws(()=>tx.preview('codex'),/符号链接/);assert.equal(fs.readdirSync(target).length,0);}));
test('damaged marker blocks preview, not overwritten',()=>fixture(home=>{fs.writeFileSync(path.join(home,'AGENTS.md'),'<!-- CHA-CODEX-POJIA:BEGIN --> partial');const tx=new SeatTransactions();tx.select(home);assert.throws(()=>tx.preview('codex'),/损坏/);}));
